# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movies.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmovies.proto\"R\n\x05Movie\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x0c\n\x04year\x18\x03 \x02(\x05\x12\x10\n\x08\x64irector\x18\x04 \x02(\t\x12\x0e\n\x06genres\x18\x05 \x03(\t\"\'\n\rMoviesDataset\x12\x16\n\x06movies\x18\x01 \x03(\x0b\x32\x06.Movie')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movies_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOVIE._serialized_start=16
  _MOVIE._serialized_end=98
  _MOVIESDATASET._serialized_start=100
  _MOVIESDATASET._serialized_end=139
# @@protoc_insertion_point(module_scope)
